server.port=8080

# Application Name
spring.application.name=quickcart-backend

# MySQL Database Configuration (Update with your MySQL credentials)
spring.datasource.url=jdbc:postgresql://72.61.229.22:5432/blinkit
spring.datasource.username=zohaibadmin
spring.datasource.password=ertIU_121
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
 
# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# JWT Configuration
jwt.secret=dGhpc2lzYXZlcnlzZWNyZXRrZXlmb3Jqd3R0b2tlbnNpbnF1aWNrY2FydGJhY2tlbmRhcHA=
jwt.expiration=86400000

